name: drm_video
description: Flutter Plugin to Play DRM Content - with every functionality provided by video_player
version: 0.0.1
homepage: https://github.com/ponnamkarthik/drm_video
issue_tracker: https://github.com/ponnamkarthik/drm_video/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.drm_video
        pluginClass: DrmVideoPlugin
      ios:
        pluginClass: DrmVideoPlugin
